apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs0
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.101.49.143
    path: "/exports"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.101.49.143
    path: "/exports"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs2
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.101.49.143
    path: "/exports"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs3
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.101.49.143
    path: "/exports"
